//! Acceptance tests for the LaunchDaemon plist generated for
//! `pmacs-vpn connect --background` on macOS (module `pmacs_vpn::launchd`).
//!
//! launchd starts system daemons with no HOME variable, which otherwise
//! breaks auth-token and config lookups inside the privileged daemon
//! process. These tests pin the workaround: the generated plist carries
//! HOME and a WorkingDirectory equal to the connecting user's home
//! directory, the plist content does not depend on the invoking process's
//! current working directory, and the plist stays a valid trigger-style
//! LaunchDaemon (no RunAtLoad, WatchPaths-driven, logging to a fixed
//! /tmp path).
//!
//! Run with: cargo test --test launchd_daemon_env_acceptance

// ============================================================================
// Small XML helpers - the plist body is generated by hand with format!, so
// these walk it as text rather than pulling in a full plist crate. They are
// deliberately whitespace-tolerant: they should keep working across
// reformatting of the generated XML, and only care about key/value pairing.
// ============================================================================

/// Return the text of the first `<string>` following `<key>{key}</key>`.
fn string_value_for_key(plist: &str, key: &str) -> Option<String> {
    let key_marker = format!("<key>{key}</key>");
    let after_key = &plist[plist.find(&key_marker)? + key_marker.len()..];
    let start = after_key.find("<string>")? + "<string>".len();
    let end = after_key[start..].find("</string>")? + start;
    Some(after_key[start..end].to_string())
}

/// Return Some(true)/Some(false) for the `<true/>`/`<false/>` boolean tag
/// immediately following `<key>{key}</key>`, or None if neither is found
/// as the very next tag.
fn bool_value_for_key(plist: &str, key: &str) -> Option<bool> {
    let key_marker = format!("<key>{key}</key>");
    let after_key = plist[plist.find(&key_marker)? + key_marker.len()..].trim_start();
    if after_key.starts_with("<true/>") {
        Some(true)
    } else if after_key.starts_with("<false/>") {
        Some(false)
    } else {
        None
    }
}

/// Return the `<string>` entries of the `<array>` following
/// `<key>{key}</key>`, in document order.
fn array_values_for_key(plist: &str, key: &str) -> Option<Vec<String>> {
    let key_marker = format!("<key>{key}</key>");
    let after_key = &plist[plist.find(&key_marker)? + key_marker.len()..];
    let array_start = after_key.find("<array>")? + "<array>".len();
    let array_end = after_key.find("</array>")?;
    let array_body = &after_key[array_start..array_end];

    let mut values = Vec::new();
    let mut rest = array_body;
    while let Some(s) = rest.find("<string>") {
        let value_start = s + "<string>".len();
        let value_end = rest[value_start..].find("</string>")? + value_start;
        values.push(rest[value_start..value_end].to_string());
        rest = &rest[value_end..];
    }
    Some(values)
}

// ============================================================================
// Criterion 1: the daemon process must receive HOME equal to the
// connecting user's home directory.
// ============================================================================

mod daemon_home_environment {
    use super::*;
    use pmacs_vpn::launchd::generate_daemon_plist;
    use std::path::PathBuf;

    // BREAKS IF: the daemon process launchd starts does not receive HOME,
    // so auth-token and config lookups relative to the user's home
    // directory silently fail inside the daemon even though the same
    // command works fine run by hand in a shell (which does have HOME).
    #[test]
    fn generated_plist_environment_variables_sets_home_to_the_connecting_users_home_dir() {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");

        let plist = generate_daemon_plist(&exe, &home);

        assert!(
            plist.contains("<key>EnvironmentVariables</key>"),
            "plist must declare an EnvironmentVariables dict for the daemon process:\n{plist}"
        );
        let home_value = string_value_for_key(&plist, "HOME");
        assert_eq!(
            home_value.as_deref(),
            Some("/Users/researcher"),
            "HOME must equal the connecting user's home directory exactly:\n{plist}"
        );
    }

    // BREAKS IF: a different user's home directory (e.g. a home path with
    // spaces, or a differently-named user) leaks the wrong or a stale HOME
    // into EnvironmentVariables instead of tracking the argument given.
    #[test]
    fn home_environment_value_tracks_the_home_dir_argument_not_a_fixed_default() {
        let exe = PathBuf::from("/opt/homebrew/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/a different user");

        let plist = generate_daemon_plist(&exe, &home);

        assert_eq!(
            string_value_for_key(&plist, "HOME").as_deref(),
            Some("/Users/a different user"),
            "HOME must reflect the actual home_dir argument, not a hardcoded value:\n{plist}"
        );
    }
}

// ============================================================================
// Criterion 2: WorkingDirectory is the user's home directory, and the
// plist is a pure function of (exe_path, home_dir) - independent of the
// process's current working directory.
// ============================================================================

mod working_directory_purity {
    use super::*;
    use pmacs_vpn::launchd::generate_daemon_plist;
    use std::path::PathBuf;

    // BREAKS IF: WorkingDirectory is left unset or derived from something
    // other than the connecting user's home, breaking relative-path
    // lookups (config, state, credentials cache) inside the daemon.
    #[test]
    fn generated_plist_working_directory_is_the_connecting_users_home_dir() {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");

        let plist = generate_daemon_plist(&exe, &home);

        assert_eq!(
            string_value_for_key(&plist, "WorkingDirectory").as_deref(),
            Some("/Users/researcher"),
            "WorkingDirectory must equal the connecting user's home directory:\n{plist}"
        );
    }

    // BREAKS IF: generate_daemon_plist reads the process's current working
    // directory (directly or via a relative path) instead of depending
    // only on its arguments. That would make `is_daemon_plist_current`
    // return a different verdict depending on where `connect` happens to
    // be invoked from, forcing a spurious admin reinstall dialog.
    //
    // This drives the purity check through the public API by holding
    // (exe_path, home_dir) fixed and varying only the process cwd; since
    // is_daemon_plist_current's verdict is entirely determined by string
    // equality against generate_daemon_plist's output (see its
    // implementation), proving the generator's output is cwd-invariant
    // proves the verdict is too. is_daemon_plist_current itself compares
    // against a real file under /Library/LaunchDaemons, which requires
    // root to write and so cannot be exercised end-to-end in this suite.
    //
    // NOTE: this test changes the process-wide current directory. It must
    // not run concurrently with other tests that depend on cwd; run this
    // binary with `--test-threads=1` if that ever becomes a concern for
    // tests added later in this file.
    #[test]
    fn plist_content_does_not_depend_on_the_processs_current_working_directory() {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");

        let original_cwd = std::env::current_dir().expect("must be able to read cwd");

        let dir_a = tempfile::tempdir().expect("tempdir a");
        let dir_b = tempfile::tempdir().expect("tempdir b");

        std::env::set_current_dir(dir_a.path()).expect("chdir into dir_a");
        let plist_from_a = generate_daemon_plist(&exe, &home);

        std::env::set_current_dir(dir_b.path()).expect("chdir into dir_b");
        let plist_from_b = generate_daemon_plist(&exe, &home);

        // Restore before asserting so a failed assertion doesn't leave the
        // process parked in a temp directory that's about to be deleted.
        std::env::set_current_dir(&original_cwd).expect("restore original cwd");

        assert_eq!(
            plist_from_a, plist_from_b,
            "plist content changed when only the process's current working \
             directory changed; generate_daemon_plist must depend solely on \
             its exe_path and home_dir arguments"
        );
    }

    // BREAKS IF: WorkingDirectory or any other field silently picks up
    // the literal string "." or an empty value when home_dir happens to
    // equal the actual cwd, masking a cwd dependency that a differing-cwd
    // test wouldn't otherwise catch.
    #[test]
    fn working_directory_is_the_full_home_path_not_a_relative_placeholder() {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");

        let plist = generate_daemon_plist(&exe, &home);
        let working_dir = string_value_for_key(&plist, "WorkingDirectory")
            .expect("WorkingDirectory key must be present");

        assert!(
            working_dir.starts_with('/'),
            "WorkingDirectory must be an absolute path, got {working_dir:?}:\n{plist}"
        );
        assert_ne!(
            working_dir, ".",
            "WorkingDirectory must not be a relative placeholder"
        );
    }
}

// ============================================================================
// Criterion 3: the plist stays a valid launchd trigger-style plist.
// ============================================================================

mod trigger_style_plist_shape {
    use super::*;
    use pmacs_vpn::launchd::{DAEMON_LABEL, TRIGGER_FILE, generate_daemon_plist};
    use std::path::PathBuf;

    fn sample_plist() -> String {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");
        generate_daemon_plist(&exe, &home)
    }

    // BREAKS IF: a syntax slip in the format! template (unescaped
    // character, unbalanced tag) produces XML that isn't well-formed;
    // `launchctl load` would then fail outright rather than misbehave, so
    // this is worth catching before it reaches a real machine.
    #[test]
    fn plist_is_well_formed_xml() {
        let plist = sample_plist();
        let mut reader = quick_xml::Reader::from_str(&plist);
        reader.config_mut().trim_text(true);

        loop {
            match reader.read_event() {
                Ok(quick_xml::events::Event::Eof) => break,
                Ok(_) => continue,
                Err(e) => panic!("generated plist is not well-formed XML: {e}\n{plist}"),
            }
        }
    }

    // BREAKS IF: RunAtLoad flips to true, which would start the daemon
    // immediately on every `launchctl load` (e.g. at every boot) instead
    // of only when the trigger file is touched by `connect`.
    #[test]
    fn run_at_load_is_false() {
        let plist = sample_plist();
        assert_eq!(
            bool_value_for_key(&plist, "RunAtLoad"),
            Some(false),
            "RunAtLoad must be false for a trigger-style daemon:\n{plist}"
        );
    }

    // BREAKS IF: WatchPaths stops pointing at the trigger-file constant
    // the rest of the crate touches to start the daemon
    // (pmacs_vpn::launchd::trigger_daemon_start), silently breaking the
    // connect flow's ability to start the privileged daemon at all.
    #[test]
    fn watch_paths_contains_the_trigger_file_constant() {
        let plist = sample_plist();
        let watch_paths =
            array_values_for_key(&plist, "WatchPaths").expect("WatchPaths must be an array");

        assert_eq!(
            watch_paths,
            vec![TRIGGER_FILE.to_string()],
            "WatchPaths must watch exactly the TRIGGER_FILE constant:\n{plist}"
        );
    }

    // BREAKS IF: ProgramArguments drifts from `<exe> connect
    // --daemon-pid=1`, either by dropping the daemon-pid flag (so the
    // spawned process doesn't know it's a daemon child) or reordering
    // arguments (clap parses positionally-sensitive subcommands).
    #[test]
    fn program_arguments_run_exe_connect_daemon_pid_1() {
        let exe = PathBuf::from("/usr/local/bin/pmacs-vpn");
        let home = PathBuf::from("/Users/researcher");
        let plist = generate_daemon_plist(&exe, &home);

        let args = array_values_for_key(&plist, "ProgramArguments")
            .expect("ProgramArguments must be an array");

        assert_eq!(
            args,
            vec![
                "/usr/local/bin/pmacs-vpn".to_string(),
                "connect".to_string(),
                "--daemon-pid=1".to_string(),
            ],
            "ProgramArguments must run `<exe> connect --daemon-pid=1` in that order:\n{plist}"
        );
    }

    // BREAKS IF: stdout/stderr stop being redirected to the fixed
    // /tmp/pmacs-vpn-daemon.log path, losing the only log trail available
    // when the daemon can't write under the user's home (see
    // open_daemon_log_file's fallback in src/main.rs).
    #[test]
    fn stdout_and_stderr_both_target_the_fixed_daemon_log_path() {
        let plist = sample_plist();

        assert_eq!(
            string_value_for_key(&plist, "StandardOutPath").as_deref(),
            Some("/tmp/pmacs-vpn-daemon.log"),
            "StandardOutPath must be the fixed daemon log path:\n{plist}"
        );
        assert_eq!(
            string_value_for_key(&plist, "StandardErrorPath").as_deref(),
            Some("/tmp/pmacs-vpn-daemon.log"),
            "StandardErrorPath must be the fixed daemon log path:\n{plist}"
        );
    }

    // BREAKS IF: the Label stops matching DAEMON_LABEL, breaking every
    // launchctl invocation elsewhere in the crate that targets the daemon
    // by that label (load/unload/installed checks).
    #[test]
    fn label_matches_the_daemon_label_constant() {
        let plist = sample_plist();
        assert_eq!(
            string_value_for_key(&plist, "Label").as_deref(),
            Some(DAEMON_LABEL),
            "Label must equal DAEMON_LABEL:\n{plist}"
        );
    }
}

// ============================================================================
// Criterion 4 (read-only source check): daemon-child log setup in
// src/main.rs must never abort the process; an unwritable log location
// must fall back to stderr logging instead of panicking.
// ============================================================================

mod daemon_log_setup_never_aborts {
    // BREAKS IF: open_daemon_log_file starts unwrapping/expecting on the
    // file-create step, so a daemon started with an unwritable or
    // missing home directory (e.g. HOME misconfigured, disk full, home
    // not yet mounted) panics on startup instead of degrading to stderr
    // logging as its own doc comment promises.
    #[test]
    fn open_daemon_log_file_body_has_no_panicking_unwrap_or_expect() {
        let src = include_str!("../src/main.rs");

        let start = src
            .find("fn open_daemon_log_file(")
            .expect("open_daemon_log_file must exist in src/main.rs");
        let after_start = &src[start..];
        let end = after_start
            .find("\n#[tokio::main]")
            .expect("open_daemon_log_file must be immediately followed by the main entry point");
        let body = &after_start[..end];

        assert!(
            !body.contains(".unwrap()"),
            "open_daemon_log_file must not unwrap() on the log file-create path:\n{body}"
        );
        assert!(
            !body.contains(".expect("),
            "open_daemon_log_file must not expect() on the log file-create path:\n{body}"
        );
    }

    // BREAKS IF: the call site that dispatches on open_daemon_log_file's
    // Option unwraps/expects instead of handling None by falling back to
    // a stderr subscriber, which would still crash the daemon even if the
    // function itself never panics.
    #[test]
    fn daemon_log_call_site_falls_back_to_stderr_on_none_instead_of_unwrapping() {
        let src = include_str!("../src/main.rs");

        let call_start = src
            .find("match open_daemon_log_file(")
            .expect("call site for open_daemon_log_file must exist in src/main.rs");
        let after_call = &src[call_start..];
        let end = after_call.find("\n    } else {").expect(
            "the daemon-child logging match must be followed by the non-daemon else branch",
        );
        let match_block = &after_call[..end];

        assert!(
            match_block.contains("None =>"),
            "the match on open_daemon_log_file's result must explicitly handle None:\n{match_block}"
        );
        assert!(
            match_block.contains("stderr"),
            "the None arm must fall back to stderr logging:\n{match_block}"
        );
        assert!(
            !match_block.contains(".unwrap()") && !match_block.contains(".expect("),
            "neither arm of the match on open_daemon_log_file's result may unwrap/expect - \
             an unwritable log location must not abort the daemon:\n{match_block}"
        );
    }
}

// ============================================================================
// Wiring: the public surface the acceptance criteria depend on must exist.
// ============================================================================

mod wiring {
    // BREAKS IF: generate_daemon_plist stops being public, so nothing
    // outside the crate (including this test suite) can verify the
    // daemon environment contract without touching the real, root-owned
    // /Library/LaunchDaemons path.
    #[test]
    fn generate_daemon_plist_is_public() {
        let _ = pmacs_vpn::launchd::generate_daemon_plist;
    }

    // BREAKS IF: is_daemon_plist_current stops being public, removing the
    // API spawn_daemon_via_launchd (src/main.rs) uses to decide whether a
    // reinstall is needed.
    #[test]
    fn is_daemon_plist_current_is_public() {
        let _ = pmacs_vpn::launchd::is_daemon_plist_current;
    }

    // BREAKS IF: the TRIGGER_FILE constant that both the plist generator
    // and trigger_daemon_start rely on stops being public/consistent.
    #[test]
    fn trigger_file_constant_is_public() {
        let _: &str = pmacs_vpn::launchd::TRIGGER_FILE;
    }
}
